name: Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Verify Git Status
      run: |
        git status
        git log -1
        git tag
      shell: pwsh

    - name: Get Previous Tag
      id: get_prev_tag
      run: |
        $prev_tag = 'v1.0.2'
        echo "PREV_TAG=$prev_tag" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "Previous tag: $prev_tag"
      shell: pwsh

    - name: Generate Changelog
      id: changelog
      run: |
        echo "Using previous tag: $env:PREV_TAG"
        if ($env:PREV_TAG) {
          $changelog = git log $env:PREV_TAG..HEAD --pretty=format:"* %s (%h)"
        } else {
          $changelog = git log HEAD --pretty=format:"* %s (%h)"
        }
        echo "Generated changelog:"
        echo $changelog
        echo "CHANGELOG=$changelog" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "CHANGELOG=$changelog"
      shell: pwsh
